#!/usr/bin/env python3
yes_no = ["yes", "no"]
directions = ["left", "right", "forward", "backward"]

#intro
name = input("What is your name adventurer?\n")
print("Greetings, " + name + ". Lets start a quest!!")
print("You are on the edge of a dark forest...")
print("Will you be able to find your way through the forest??\n")

# start of the game
response = ""
while response not in y_n:
    response = input("Would you step into the forest?\y/n'n")
    if response == "y":
        print( "You begin walking into the forest and you hear strange sounds coming from every direction..." )
    elif response == "n":
	 print("You are currently unable to complete this quest. Goodbye, " + name + ".")
	quit()
    else print("I'm sorry... I did not understand that... please try again.")

# the next part of the game
response = ""
while response not in directions:
   print("To your left, you see a bear.")
    print("To your right, there is more forest.")
    print("There is a rock wall directly in front of you.")
    print("Behind you is the forest exit.\n")
    response = input("What direction do you move?\nleft/right/forward/backward\n")
    if response == "left":
        print("The bear eats you. Farewell, " + name + ".")
        quit()
    elif response == "right":
        print("You head deeper into the forest.\n")
    elif response == "forward":
        print("You cannot scale the wall.\n")
        response = "" 
    elif response == "backward":
        print("You leave the forest. Goodbye, " + name + ".")
        quit()
    else:
        print("I didn't understand that.\n") 
		
